<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MU_Mu6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m_U.Mu6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m_U.Mu6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'associationGrouping' => ['privates', '.errored..service_locator.m_U.Mu6.App\\Entity\\Framework\\LsDefAssociationGrouping', NULL, 'Cannot autowire service ".service_locator.m_U.Mu6": it references class "App\\Entity\\Framework\\LsDefAssociationGrouping" but no such service exists.'],
        ], [
            'associationGrouping' => 'App\\Entity\\Framework\\LsDefAssociationGrouping',
        ]);
    }
}
