<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AzwNnXPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AzwNnXP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AzwNnXP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'targetUser' => ['privates', '.errored..service_locator.AzwNnXP.App\\Entity\\User\\User', NULL, 'Cannot autowire service ".service_locator.AzwNnXP": it references class "App\\Entity\\User\\User" but no such service exists.'],
        ], [
            'targetUser' => 'App\\Entity\\User\\User',
        ]);
    }
}
