<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TbTRhyTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TbTRhyT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TbTRhyT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bucket' => ['privates', 'App\\Service\\BucketService', 'getBucketServiceService', true],
            'doc' => ['privates', '.errored..service_locator.TbTRhyT.App\\Entity\\Framework\\LsDoc', NULL, 'Cannot autowire service ".service_locator.TbTRhyT": it references class "App\\Entity\\Framework\\LsDoc" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.TbTRhyT.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.TbTRhyT": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'bucket' => 'App\\Service\\BucketService',
            'doc' => 'App\\Entity\\Framework\\LsDoc',
            'user' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
