<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tx4lsi1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Tx4lsi1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Tx4lsi1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mirrorServer' => ['privates', 'App\\Service\\MirrorServer', 'getMirrorServerService', true],
            'server' => ['privates', '.errored..service_locator.Tx4lsi1.App\\Entity\\Framework\\Mirror\\Server', NULL, 'Cannot autowire service ".service_locator.Tx4lsi1": it references class "App\\Entity\\Framework\\Mirror\\Server" but no such service exists.'],
        ], [
            'mirrorServer' => 'App\\Service\\MirrorServer',
            'server' => 'App\\Entity\\Framework\\Mirror\\Server',
        ]);
    }
}
