<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NXXMC5eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NXXMC5e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NXXMC5e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'additionalField' => ['privates', '.errored..service_locator.NXXMC5e.App\\Entity\\Framework\\AdditionalField', NULL, 'Cannot autowire service ".service_locator.NXXMC5e": it references class "App\\Entity\\Framework\\AdditionalField" but no such service exists.'],
        ], [
            'additionalField' => 'App\\Entity\\Framework\\AdditionalField',
        ]);
    }
}
