<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZxADY0NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZxADY0N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZxADY0N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lsDefGrade' => ['privates', '.errored..service_locator.ZxADY0N.App\\Entity\\Framework\\LsDefGrade', NULL, 'Cannot autowire service ".service_locator.ZxADY0N": it references class "App\\Entity\\Framework\\LsDefGrade" but no such service exists.'],
        ], [
            'lsDefGrade' => 'App\\Entity\\Framework\\LsDefGrade',
        ]);
    }
}
