<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VCMnsVUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VCMnsVU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VCMnsVU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lsAssociation' => ['privates', '.errored..service_locator.VCMnsVU.App\\Entity\\Framework\\LsAssociation', NULL, 'Cannot autowire service ".service_locator.VCMnsVU": it references class "App\\Entity\\Framework\\LsAssociation" but no such service exists.'],
        ], [
            'lsAssociation' => 'App\\Entity\\Framework\\LsAssociation',
        ]);
    }
}
