<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WDiCgSwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WDiCgSw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WDiCgSw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lsDefSubject' => ['privates', '.errored..service_locator.WDiCgSw.App\\Entity\\Framework\\LsDefSubject', NULL, 'Cannot autowire service ".service_locator.WDiCgSw": it references class "App\\Entity\\Framework\\LsDefSubject" but no such service exists.'],
        ], [
            'lsDefSubject' => 'App\\Entity\\Framework\\LsDefSubject',
        ]);
    }
}
