<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KmuVa3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._kmuVa3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._kmuVa3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'framework' => ['privates', '.errored..service_locator._kmuVa3.App\\Entity\\Framework\\Mirror\\Framework', NULL, 'Cannot autowire service ".service_locator._kmuVa3": it references class "App\\Entity\\Framework\\Mirror\\Framework" but no such service exists.'],
        ], [
            'framework' => 'App\\Entity\\Framework\\Mirror\\Framework',
        ]);
    }
}
