<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAsnImportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AsnImport' shared autowired service.
     *
     * @return \App\Service\AsnImport
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/AsnImport.php';

        return $container->privates['App\\Service\\AsnImport'] = new \App\Service\AsnImport(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['csa_guzzle.client.json'] ?? $container->load('getCsaGuzzle_Client_JsonService')));
    }
}
