<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApi1RouteMapService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\Api1RouteMap' shared autowired service.
     *
     * @return \App\Service\Api1RouteMap
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Api1RouteMap.php';

        return $container->services['App\\Service\\Api1RouteMap'] = new \App\Service\Api1RouteMap();
    }
}
