<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdditionalFieldControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Framework\AdditionalFieldController' shared autowired service.
     *
     * @return \App\Controller\Framework\AdditionalFieldController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Framework/AdditionalFieldController.php';

        $container->services['App\\Controller\\Framework\\AdditionalFieldController'] = $instance = new \App\Controller\Framework\AdditionalFieldController(($container->privates['App\\Repository\\Framework\\AdditionalFieldRepository'] ?? $container->load('getAdditionalFieldRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.zCZyUMB'] ?? $container->load('get_ServiceLocator_ZCZyUMBService'))->withContext('App\\Controller\\Framework\\AdditionalFieldController', $container));

        return $instance;
    }
}
