<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBucketFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\BucketFactory' shared autowired service.
     *
     * @return \App\Service\BucketFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/BucketFactory.php';

        return $container->privates['App\\Service\\BucketFactory'] = new \App\Service\BucketFactory(($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))));
    }
}
