<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBucketServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\BucketService' shared autowired service.
     *
     * @return \App\Service\BucketService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/BucketService.php';

        return $container->privates['App\\Service\\BucketService'] = new \App\Service\BucketService(($container->privates['League\\Flysystem\\Filesystem'] ?? $container->load('getFilesystem2Service')), $container->getEnv('ATTACHMENT_URL_PREFIX'), $container->getEnv('AWS_S3_PREFIX'));
    }
}
