<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCaseV1P0ControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\CaseV1P0Controller' shared autowired service.
     *
     * @return \App\Controller\Api\CaseV1P0Controller
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/log/Psr/Log/LoggerTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Service/LoggerTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/CaseV1P0Controller.php';

        $container->services['App\\Controller\\Api\\CaseV1P0Controller'] = $instance = new \App\Controller\Api\CaseV1P0Controller(($container->services['jms_serializer'] ?? $container->load('getJmsSerializerService')), '190202');

        $instance->setContainer(($container->privates['.service_locator.zCZyUMB'] ?? $container->load('get_ServiceLocator_ZCZyUMBService'))->withContext('App\\Controller\\Api\\CaseV1P0Controller', $container));
        $instance->setLogger(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));

        return $instance;
    }
}
