<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsaGuzzle_Middleware_HistoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'csa_guzzle.middleware.history' shared service.
     *
     * @return \Csa\GuzzleHttp\Middleware\History\HistoryMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/csa/guzzle-history-middleware/src/HistoryMiddleware.php';

        return $container->privates['csa_guzzle.middleware.history'] = new \Csa\GuzzleHttp\Middleware\History\HistoryMiddleware(($container->services['csa_guzzle.data_collector.history_bag'] ?? ($container->services['csa_guzzle.data_collector.history_bag'] = new \Csa\GuzzleHttp\Middleware\History\History())));
    }
}
