<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcelExportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ExcelExport' shared autowired service.
     *
     * @return \App\Service\ExcelExport
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ExcelExport.php';

        return $container->privates['App\\Service\\ExcelExport'] = new \App\Service\ExcelExport(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
