<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportCaseJsonCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Console\Import\ImportCaseJsonCommand' shared autowired service.
     *
     * @return \App\Console\Import\ImportCaseJsonCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Console/BaseDispatchingCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Console/BaseDoctrineCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Console/Import/ImportCaseJsonCommand.php';

        $container->privates['App\\Console\\Import\\ImportCaseJsonCommand'] = $instance = new \App\Console\Import\ImportCaseJsonCommand(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setName('import:case-json');

        return $instance;
    }
}
