<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItemVoterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\Voter\ItemVoter' shared autowired service.
     *
     * @return \App\Security\Voter\ItemVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/Voter.php';
        include_once \dirname(__DIR__, 4).'/src/Security/Voter/DeferDecisionTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Security/Voter/RoleCheckTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Security/Voter/ItemVoter.php';

        $container->privates['App\\Security\\Voter\\ItemVoter'] = $instance = new \App\Security\Voter\ItemVoter();

        $instance->setDecisionManager(($container->privates['debug.security.access.decision_manager'] ?? $container->getDebug_Security_Access_DecisionManagerService()));
        $instance->setRoleChecker(($container->privates['security.role_hierarchy'] ?? $container->getSecurity_RoleHierarchyService()));

        return $instance;
    }
}
