<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportGeneric1CommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Console\Import\ImportGeneric1Command' shared autowired service.
     *
     * @return \App\Console\Import\ImportGeneric1Command
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Console/BaseDispatchingCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Console/Import/ImportGeneric1Command.php';

        $container->privates['App\\Console\\Import\\ImportGeneric1Command'] = $instance = new \App\Console\Import\ImportGeneric1Command(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));

        $instance->setName('import:generic-csv');

        return $instance;
    }
}
