<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLsDoc5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KmOPVtE.App\Entity\Framework\LsDoc' shared service.
     *
     * @return \App\Entity\Framework\LsDoc
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.KmOPVtE": it references class "App\\Entity\\Framework\\LsDoc" but no such service exists.');
    }
}
