<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginCaptchaListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\LoginCaptchaListener' shared autowired service.
     *
     * @return \App\EventListener\LoginCaptchaListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/LoginCaptchaListener.php';

        return $container->privates['App\\EventListener\\LoginCaptchaListener'] = new \App\EventListener\LoginCaptchaListener($container->getEnv('GOOGLE_CAPTCHA_SECRET_KEY'));
    }
}
