<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLsDefConceptService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NCK.VRn.App\Entity\Framework\LsDefConcept' shared service.
     *
     * @return \App\Entity\Framework\LsDefConcept
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.NCK.VRn": it references class "App\\Entity\\Framework\\LsDefConcept" but no such service exists.');
    }
}
