<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLsAssociation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xS1kUvg.App\Entity\Framework\LsAssociation' shared service.
     *
     * @return \App\Entity\Framework\LsAssociation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.xS1kUvg": it references class "App\\Entity\\Framework\\LsAssociation" but no such service exists.');
    }
}
