<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLsDefItemTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.109wlF9.App\Entity\Framework\LsDefItemType' shared service.
     *
     * @return \App\Entity\Framework\LsDefItemType
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.109wlF9": it references class "App\\Entity\\Framework\\LsDefItemType" but no such service exists.');
    }
}
