<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLsItem5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Jlt.5eM.App\Entity\Framework\LsItem' shared service.
     *
     * @return \App\Entity\Framework\LsItem
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Jlt.5eM": it references class "App\\Entity\\Framework\\LsItem" but no such service exists.');
    }
}
