<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManageMirrorVoterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\Voter\ManageMirrorVoter' shared autowired service.
     *
     * @return \App\Security\Voter\ManageMirrorVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/Voter.php';
        include_once \dirname(__DIR__, 4).'/src/Security/Voter/RoleCheckTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Security/Voter/ManageMirrorVoter.php';

        $container->privates['App\\Security\\Voter\\ManageMirrorVoter'] = $instance = new \App\Security\Voter\ManageMirrorVoter();

        $instance->setRoleChecker(($container->privates['security.role_hierarchy'] ?? $container->getSecurity_RoleHierarchyService()));

        return $instance;
    }
}
