<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationLoggingListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\NotificationLoggingListener' shared autowired service.
     *
     * @return \App\EventListener\NotificationLoggingListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/psr/log/Psr/Log/LoggerTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Service/LoggerTrait.php';
        include_once \dirname(__DIR__, 4).'/src/EventListener/NotificationLoggingListener.php';

        $container->privates['App\\EventListener\\NotificationLoggingListener'] = $instance = new \App\EventListener\NotificationLoggingListener();

        $instance->setLogger(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));

        return $instance;
    }
}
