<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOAuthServiceControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\User\OAuthServiceController' shared autowired service.
     *
     * @return \App\Controller\User\OAuthServiceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CommandDispatcherTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/User/OAuthServiceController.php';

        $container->services['App\\Controller\\User\\OAuthServiceController'] = $instance = new \App\Controller\User\OAuthServiceController($container->getEnv('GITHUB_CLIENT_ID'), $container->getEnv('GITHUB_CLIENT_SECRET'), (($container->hasParameter("github_redirect_uri")) ? ($container->getParameter("github_redirect_uri")) : (null)));

        $instance->setContainer(($container->privates['.service_locator.zCZyUMB'] ?? $container->load('get_ServiceLocator_ZCZyUMBService'))->withContext('App\\Controller\\User\\OAuthServiceController', $container));
        $instance->setDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));

        return $instance;
    }
}
