<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPackageTransformerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataTransformer\CaseJson\PackageTransformer' shared autowired service.
     *
     * @return \App\DataTransformer\CaseJson\PackageTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/DataTransformer/CaseJson/PackageTransformer.php';

        return $container->privates['App\\DataTransformer\\CaseJson\\PackageTransformer'] = new \App\DataTransformer\CaseJson\PackageTransformer(($container->privates['App\\DataTransformer\\CaseJson\\DefinitionsTransformer'] ?? $container->load('getDefinitionsTransformerService')), ($container->privates['App\\DataTransformer\\CaseJson\\DocumentTransformer'] ?? $container->load('getDocumentTransformerService')), ($container->privates['App\\DataTransformer\\CaseJson\\ItemsTransformer'] ?? $container->load('getItemsTransformerService')), ($container->privates['App\\DataTransformer\\CaseJson\\AssociationsTransformer'] ?? $container->load('getAssociationsTransformerService')), ($container->privates['App\\DataTransformer\\CaseJson\\RubricsTransformer'] ?? $container->load('getRubricsTransformerService')));
    }
}
