<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Config_SessionCheckService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.config.session_check' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

        return $container->privates['security.firewall.map.config.session_check'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('session_check', 'security.user_checker', '.security.request_matcher.WijBsVl', false, false, '', '', '', '', '', [], NULL);
    }
}
