<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AxoVGUV.App\Entity\Framework\Mirror\Server' shared service.
     *
     * @return \App\Entity\Framework\Mirror\Server
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.AxoVGUV": it references class "App\\Entity\\Framework\\Mirror\\Server" but no such service exists.');
    }
}
