<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSignupControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\User\SignupController' shared autowired service.
     *
     * @return \App\Controller\User\SignupController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CommandDispatcherTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/User/SignupController.php';

        $container->services['App\\Controller\\User\\SignupController'] = $instance = new \App\Controller\User\SignupController(($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')), $container->getEnv('MAIL_FEATURE_FROM_EMAIL'), 'dev');

        $instance->setContainer(($container->privates['.service_locator.zCZyUMB'] ?? $container->load('get_ServiceLocator_ZCZyUMBService'))->withContext('App\\Controller\\User\\SignupController', $container));
        $instance->setDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));

        return $instance;
    }
}
