<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSession_Handler_PdoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'session.handler.pdo' shared autowired service.
     *
     * @return \Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Session/Storage/Handler/AbstractSessionHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/Session/Storage/Handler/PdoSessionHandler.php';

        return $container->privates['session.handler.pdo'] = new \Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler('mysql:host='.$container->getEnv('string:MYSQL_HOST').';port='.$container->getEnv('string:int:MYSQL_PORT').';dbname='.$container->getEnv('string:MYSQL_DATABASE'), ['db_username' => $container->getEnv('MYSQL_USER'), 'db_password' => $container->getEnv('MYSQL_PASSWORD'), 'db_table' => 'auth_session', 'db_id_col' => 'id', 'db_connection_options' => NULL]);
    }
}
