<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSystemLogControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SystemLogController' shared autowired service.
     *
     * @return \App\Controller\SystemLogController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SystemLogController.php';

        $container->services['App\\Controller\\SystemLogController'] = $instance = new \App\Controller\SystemLogController(($container->services['simplethings_entityaudit.reader'] ?? $container->load('getSimplethingsEntityaudit_ReaderService')), ($container->privates['App\\Repository\\ChangeEntryRepository'] ?? $container->load('getChangeEntryRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.zCZyUMB'] ?? $container->load('get_ServiceLocator_ZCZyUMBService'))->withContext('App\\Controller\\SystemLogController', $container));

        return $instance;
    }
}
