<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateListCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Console\Mirror\UpdateListCommand' shared autowired service.
     *
     * @return \App\Console\Mirror\UpdateListCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Console/Mirror/UpdateListCommand.php';

        $container->privates['App\\Console\\Mirror\\UpdateListCommand'] = $instance = new \App\Console\Mirror\UpdateListCommand(($container->privates['App\\Service\\MirrorServer'] ?? $container->load('getMirrorServerService')));

        $instance->setName('jobs:update-next-server');

        return $instance;
    }
}
