<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAddRoleCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.App\Console\User\UserAddRoleCommand' shared autowired service.
     *
     * @return \App\Console\User\UserAddRoleCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Console/BaseDispatchingCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Console/User/UserRoleCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Console/User/UserAddRoleCommand.php';

        return $container->services['console.command.public_alias.App\\Console\\User\\UserAddRoleCommand'] = new \App\Console\User\UserAddRoleCommand(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
