<?php

namespace Container0c1jj5c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUuidNormalizerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'GBProd\UuidNormalizer\UuidNormalizer' shared autowired service.
     *
     * @return \GBProd\UuidNormalizer\UuidNormalizer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/NormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/gbprod/uuid-normalizer/src/UuidNormalizer.php';

        return $container->privates['GBProd\\UuidNormalizer\\UuidNormalizer'] = new \GBProd\UuidNormalizer\UuidNormalizer();
    }
}
