<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPpHIGmv\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPpHIGmv/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPpHIGmv.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPpHIGmv\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerPpHIGmv\App_KernelProdContainer([
    'container.build_hash' => 'PpHIGmv',
    'container.build_id' => '3595b328',
    'container.build_time' => 1600221020,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPpHIGmv');
