<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jlt_5eMService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Jlt.5eM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Jlt.5eM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lsItem' => ['privates', '.errored..service_locator.Jlt.5eM.App\\Entity\\Framework\\LsItem', NULL, 'Cannot autowire service ".service_locator.Jlt.5eM": it references class "App\\Entity\\Framework\\LsItem" but no such service exists.'],
        ], [
            'lsItem' => 'App\\Entity\\Framework\\LsItem',
        ]);
    }
}
