<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AxoVGUVService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.AxoVGUV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AxoVGUV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'server' => ['privates', '.errored..service_locator.AxoVGUV.App\\Entity\\Framework\\Mirror\\Server', NULL, 'Cannot autowire service ".service_locator.AxoVGUV": it references class "App\\Entity\\Framework\\Mirror\\Server" but no such service exists.'],
        ], [
            'server' => 'App\\Entity\\Framework\\Mirror\\Server',
        ]);
    }
}
