<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdditionalFieldControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Framework\AdditionalFieldController' shared autowired service.
     *
     * @return \App\Controller\Framework\AdditionalFieldController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Framework\\AdditionalFieldController'] = $instance = new \App\Controller\Framework\AdditionalFieldController(($container->privates['App\\Repository\\Framework\\AdditionalFieldRepository'] ?? $container->load('getAdditionalFieldRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.zCZyUMB'] ?? $container->load('get_ServiceLocator_ZCZyUMBService'))->withContext('App\\Controller\\Framework\\AdditionalFieldController', $container));

        return $instance;
    }
}
