<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAboutControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Site\AboutController' shared autowired service.
     *
     * @return \App\Controller\Site\AboutController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Site\\AboutController'] = $instance = new \App\Controller\Site\AboutController(\dirname(__DIR__, 4));

        $instance->setContainer(($container->privates['.service_locator.zCZyUMB'] ?? $container->load('get_ServiceLocator_ZCZyUMBService'))->withContext('App\\Controller\\Site\\AboutController', $container));

        return $instance;
    }
}
