<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBucketServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\BucketService' shared autowired service.
     *
     * @return \App\Service\BucketService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\BucketService'] = new \App\Service\BucketService(new \League\Flysystem\Filesystem((new \App\Service\BucketFactory(($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)))))->filesystem()), $container->getEnv('ATTACHMENT_URL_PREFIX'), $container->getEnv('AWS_S3_PREFIX'));
    }
}
