<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CommentsController' shared autowired service.
     *
     * @return \App\Controller\CommentsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CommentsController'] = $instance = new \App\Controller\CommentsController(($container->services['jms_serializer'] ?? $container->load('getJmsSerializerService')), ($container->services['qandidate.toggle.manager'] ?? $container->getQandidate_Toggle_ManagerService()), ($container->services['qandidate.toggle.user_context_factory'] ?? $container->getQandidate_Toggle_UserContextFactoryService()));

        $instance->setContainer(($container->privates['.service_locator.zCZyUMB'] ?? $container->load('get_ServiceLocator_ZCZyUMBService'))->withContext('App\\Controller\\CommentsController', $container));
        $instance->setDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));

        return $instance;
    }
}
