<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsaGuzzle_DataCollector_HistoryBagService extends App_KernelProdContainer
{
    /*
     * Gets the public 'csa_guzzle.data_collector.history_bag' shared service.
     *
     * @return \Csa\GuzzleHttp\Middleware\History\History
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['csa_guzzle.data_collector.history_bag'] = new \Csa\GuzzleHttp\Middleware\History\History();
    }
}
