<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCaseUriRuntimeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Twig\Extension\CaseUriRuntime' shared autowired service.
     *
     * @return \App\Twig\Extension\CaseUriRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Twig\\Extension\\CaseUriRuntime'] = new \App\Twig\Extension\CaseUriRuntime(($container->privates['App\\Service\\UriGenerator'] ?? $container->load('getUriGeneratorService')), ($container->services['router'] ?? $container->getRouterService()), ($container->privates['App\\Service\\IdentifiableObjectHelper'] ?? $container->load('getIdentifiableObjectHelperService')));
    }
}
