<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCfRubricCriterionLevelRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\Framework\CfRubricCriterionLevelRepository' shared autowired service.
     *
     * @return \App\Repository\Framework\CfRubricCriterionLevelRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\Framework\\CfRubricCriterionLevelRepository'] = new \App\Repository\Framework\CfRubricCriterionLevelRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
