<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcelExportControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ExcelExportController' shared autowired service.
     *
     * @return \App\Controller\ExcelExportController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ExcelExportController'] = $instance = new \App\Controller\ExcelExportController(new \App\Service\ExcelExport(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'))));

        $instance->setContainer(($container->privates['.service_locator.zCZyUMB'] ?? $container->load('get_ServiceLocator_ZCZyUMBService'))->withContext('App\\Controller\\ExcelExportController', $container));
        $instance->setDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));

        return $instance;
    }
}
