<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrameworkService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator._kmuVa3.App\Entity\Framework\Mirror\Framework' shared service.
     *
     * @return \App\Entity\Framework\Mirror\Framework
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._kmuVa3": it references class "App\\Entity\\Framework\\Mirror\\Framework" but no such service exists.');
    }
}
