<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGithubImportService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\GithubImport' shared autowired service.
     *
     * @return \App\Service\GithubImport
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\GithubImport'] = new \App\Service\GithubImport(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
