<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportExcelFileHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Handler\Import\ImportExcelFileHandler' shared autowired service.
     *
     * @return \App\Handler\Import\ImportExcelFileHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        return $container->privates['App\\Handler\\Import\\ImportExcelFileHandler'] = new \App\Handler\Import\ImportExcelFileHandler(($container->services['validator'] ?? $container->load('getValidatorService')), $a, new \App\Service\ExcelImport($a));
    }
}
