<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportAsnFromUrlHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Handler\Import\ImportAsnFromUrlHandler' shared autowired service.
     *
     * @return \App\Handler\Import\ImportAsnFromUrlHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        return $container->privates['App\\Handler\\Import\\ImportAsnFromUrlHandler'] = new \App\Handler\Import\ImportAsnFromUrlHandler(($container->services['validator'] ?? $container->load('getValidatorService')), $a, new \App\Service\AsnImport($a, ($container->services['csa_guzzle.client.json'] ?? $container->load('getCsaGuzzle_Client_JsonService'))));
    }
}
