<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportAsnCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Console\Import\ImportAsnCommand' shared autowired service.
     *
     * @return \App\Console\Import\ImportAsnCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Console\\Import\\ImportAsnCommand'] = $instance = new \App\Console\Import\ImportAsnCommand(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));

        $instance->setName('import:asn');

        return $instance;
    }
}
