<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_FormErrorHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'jms_serializer.form_error_handler' shared service.
     *
     * @return \JMS\Serializer\Handler\FormErrorHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['jms_serializer.form_error_handler'] = new \JMS\Serializer\Handler\FormErrorHandler(($container->services['translator'] ?? $container->load('getTranslatorService')), 'validators');
    }
}
