<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLsDoc9Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.yy09t2m.App\Entity\Framework\LsDoc' shared service.
     *
     * @return \App\Entity\Framework\LsDoc
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.yy09t2m": it references class "App\\Entity\\Framework\\LsDoc" but no such service exists.');
    }
}
