<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLsDefGradeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\Framework\LsDefGradeRepository' shared autowired service.
     *
     * @return \App\Repository\Framework\LsDefGradeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\Framework\\LsDefGradeRepository'] = new \App\Repository\Framework\LsDefGradeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
