<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLsItem2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.2xms8xd.App\Entity\Framework\LsItem' shared service.
     *
     * @return \App\Entity\Framework\LsItem
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.2xms8xd": it references class "App\\Entity\\Framework\\LsItem" but no such service exists.');
    }
}
