<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLsDocAttributeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\Framework\LsDocAttributeRepository' shared autowired service.
     *
     * @return \App\Repository\Framework\LsDocAttributeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\Framework\\LsDocAttributeRepository'] = new \App\Repository\Framework\LsDocAttributeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
