<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLsDefGradeService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.ZxADY0N.App\Entity\Framework\LsDefGrade' shared service.
     *
     * @return \App\Entity\Framework\LsDefGrade
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ZxADY0N": it references class "App\\Entity\\Framework\\LsDefGrade" but no such service exists.');
    }
}
