<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMirrorFrameworkService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\MirrorFramework' shared autowired service.
     *
     * @return \App\Service\MirrorFramework
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Service\\MirrorFramework'] = $instance = new \App\Service\MirrorFramework(($container->privates['App\\Service\\MirrorServer'] ?? $container->load('getMirrorServerService')), ($container->services['doctrine'] ?? $container->getDoctrineService()));

        $instance->setDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
        $instance->setLogger(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));

        return $instance;
    }
}
