<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationLoggingListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventListener\NotificationLoggingListener' shared autowired service.
     *
     * @return \App\EventListener\NotificationLoggingListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\EventListener\\NotificationLoggingListener'] = $instance = new \App\EventListener\NotificationLoggingListener();

        $instance->setLogger(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));

        return $instance;
    }
}
