<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioSecurity_UaParser_UaPhpService extends App_KernelProdContainer
{
    /*
     * Gets the public 'nelmio_security.ua_parser.ua_php' shared service.
     *
     * @return \Nelmio\SecurityBundle\UserAgent\UAFamilyParser\UAFamilyParser
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['nelmio_security.ua_parser.ua_php'] = new \Nelmio\SecurityBundle\UserAgent\UAFamilyParser\UAFamilyParser(($container->privates['nelmio_security.ua_parser.ua_php.provider'] ?? $container->load('getNelmioSecurity_UaParser_UaPhp_ProviderService')));
    }
}
