<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOAuthCredentialService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.3imnR1P.App\Entity\Framework\Mirror\OAuthCredential' shared service.
     *
     * @return \App\Entity\Framework\Mirror\OAuthCredential
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.3imnR1P": it references class "App\\Entity\\Framework\\Mirror\\OAuthCredential" but no such service exists.');
    }
}
