<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordFieldValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Validator\Constraints\PasswordFieldValidator' shared autowired service.
     *
     * @return \App\Validator\Constraints\PasswordFieldValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Validator\\Constraints\\PasswordFieldValidator'] = new \App\Validator\Constraints\PasswordFieldValidator();
    }
}
