<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\User\SecurityController' shared autowired service.
     *
     * @return \App\Controller\User\SecurityController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\User\\SecurityController'] = $instance = new \App\Controller\User\SecurityController(($container->services['security.authentication_utils'] ?? $container->load('getSecurity_AuthenticationUtilsService')));

        $instance->setContainer(($container->privates['.service_locator.zCZyUMB'] ?? $container->load('get_ServiceLocator_ZCZyUMBService'))->withContext('App\\Controller\\User\\SecurityController', $container));

        return $instance;
    }
}
