<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendEmailCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Symfony\Bundle\SwiftmailerBundle\Command\SendEmailCommand' shared autowired service.
     *
     * @return \Symfony\Bundle\SwiftmailerBundle\Command\SendEmailCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Symfony\\Bundle\\SwiftmailerBundle\\Command\\SendEmailCommand'] = $instance = new \Symfony\Bundle\SwiftmailerBundle\Command\SendEmailCommand();

        $instance->setName('swiftmailer:spool:send');

        return $instance;
    }
}
