<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSignupControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\User\SignupController' shared autowired service.
     *
     * @return \App\Controller\User\SignupController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\User\\SignupController'] = $instance = new \App\Controller\User\SignupController(($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')), $container->getEnv('MAIL_FEATURE_FROM_EMAIL'), 'prod');

        $instance->setContainer(($container->privates['.service_locator.zCZyUMB'] ?? $container->load('get_ServiceLocator_ZCZyUMBService'))->withContext('App\\Controller\\User\\SignupController', $container));
        $instance->setDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));

        return $instance;
    }
}
