<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSimplethingsEntityaudit_ConfigService extends App_KernelProdContainer
{
    /*
     * Gets the public 'simplethings_entityaudit.config' shared service.
     *
     * @return \SimpleThings\EntityAudit\AuditConfiguration
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['simplethings_entityaudit.config'] = $instance = new \SimpleThings\EntityAudit\AuditConfiguration();

        $instance->setAuditedEntityClasses($container->parameters['simplethings.entityaudit.audited_entities']);
        $instance->setGlobalIgnoreColumns($container->parameters['simplethings.entityaudit.global_ignore_columns']);
        $instance->setTablePrefix('audit_');
        $instance->setTableSuffix('');
        $instance->setRevisionTableName('audit_revision');
        $instance->setRevisionIdFieldType('integer');
        $instance->setRevisionFieldName('rev');
        $instance->setRevisionTypeFieldName('revtype');
        $instance->setUsernameCallable(new \SimpleThings\EntityAudit\User\TokenStorageUsernameCallable($container));

        return $instance;
    }
}
