<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServer2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Q_TN9zW.App\Entity\Framework\Mirror\Server' shared service.
     *
     * @return \App\Entity\Framework\Mirror\Server
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Q_TN9zW": it references class "App\\Entity\\Framework\\Mirror\\Server" but no such service exists.');
    }
}
