<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateFrameworkHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Handler\Framework\UpdateFrameworkHandler' shared autowired service.
     *
     * @return \App\Handler\Framework\UpdateFrameworkHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        return $container->privates['App\\Handler\\Framework\\UpdateFrameworkHandler'] = new \App\Handler\Framework\UpdateFrameworkHandler(($container->services['validator'] ?? $container->load('getValidatorService')), $a, new \App\Service\FrameworkUpdater($a, ($container->privates['App\\Service\\GithubImport'] ?? $container->load('getGithubImportService'))));
    }
}
