<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAddRoleCommandService extends App_KernelProdContainer
{
    /*
     * Gets the public 'console.command.public_alias.App\Console\User\UserAddRoleCommand' shared autowired service.
     *
     * @return \App\Console\User\UserAddRoleCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.App\\Console\\User\\UserAddRoleCommand'] = new \App\Console\User\UserAddRoleCommand(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
