<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUriGeneratorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\UriGenerator' shared autowired service.
     *
     * @return \App\Service\UriGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\UriGenerator'] = new \App\Service\UriGenerator(($container->services['router'] ?? $container->getRouterService()));
    }
}
