<?php

namespace ContainerPpHIGmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDocAclRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\User\UserDocAclRepository' shared autowired service.
     *
     * @return \App\Repository\User\UserDocAclRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\User\\UserDocAclRepository'] = new \App\Repository\User\UserDocAclRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
