<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0c1jj5c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0c1jj5c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0c1jj5c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0c1jj5c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0c1jj5c\App_KernelDevDebugContainer([
    'container.build_hash' => '0c1jj5c',
    'container.build_id' => 'f2b754a5',
    'container.build_time' => 1600221045,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0c1jj5c');
